title: Zeyu Wang's Homepage
page-top-title: Zeyu Wang
top-section-bg-text: Computer vision, information interpretation, and perception 
home-subtitle: Zeyu Wang&ensp;|&ensp;王泽煜
copyright-text: '&copy; Zeyu Wang 2023-2024. All Rights Reserved.'
